version: 2
jobs:
  build:
    working_directory: ~/bulk-api-python-client
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ checksum "setup.py" }}
      - run:
          command: |
            sudo pip install -e .[dev]
      - save_cache:
          key: deps9-{{ checksum "setup.py" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          command: |
            pytest
      - run:
          command: |
            black --check .
  deploy_prod:
    working_directory: ~/bulk-api-python-client
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ checksum "setup.py" }}
      - run:
          command: |
            sudo pip install -e .[dev]
      - save_cache:
          key: deps9-{{ checksum "setup.py" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - add_ssh_keys:
          fingerprints:
            - "7e:ea:bf:b3:d4:c5:d2:ed:78:40:e1:47:34:58:2a:b9"
      - run:
          command: |
            git clone --single-branch --branch gh-pages git@github.com:pivotbio/bulk-api-python-client.git docs
            cd docs
            git rm . -rf
            cd ..
            pdoc --html --output-dir docs/ bulk_api_client --force
            cd docs
            git config user.email "ci-build@pivotbio.com"
            git config user.name "ci-build"
            git add -A
            git diff-index --quiet HEAD || git commit -m "[skip ci] update docs after build"
            git push origin gh-pages

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only: never
